language: java

jdk:
  - openjdk8

# To increase the memory size available during Travis build.
sudo: required

env:
  global:
    # https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
    # Encrypted `GCS_SECRET` variable.
    - secure: "i/Kdj+APEvQPULnFU05hYJp1AG+NYS10XapkrGP4S/uXcfFyGAdjyH/BzPoSsg1wvhtySLD0OS1hDoHiJ1wYsqHskkQZDodu29HcTxpMi1qbKqWly6E73eKDr5tMBfFTOMQDAzKbp5T1/NxMtV7T4Dhoam0EdbdHj6ui5B53SVPF12H7fnmVZurpFWvGwS75O6N2GJMOsyK8tLa2SqMNvYTWHQL5CgnOX5yszAm1/WVCmxvIygHvvQ0J4DYg2KGjePSYKTPyN+MCK4rxKZnzy4x+bUOhks+lDFuyAKQbY57cA6hkUkB+pXePPtZr0rAHamaAdKZiBaJ0S1FtZKdUuC6FP1fAxsOgoNsuyYdcFqekDIw595F7p1TVDsjOtWVTeAHxAIWqC1pweUnRuAMzy/5JVGb3Vmdgiq1okL6owiy+d93DVAW/47+HUaQL09gnd4TlnJvC54gfexchQJwLmX+yEFTKgDvwqhQcCpkZoIZhAeNz3E5okGtTNhvlVJ0+jKuHYpx17yrvC0Y45LGKBdgttfGL/9GOjpfk4TeCo6o1VqlCzv0j2y0K3gkTM7su6PGFkkQ20UPfjTNvlcvEHHYWtgGVaRgAmPyjKRQrHyTMPmbHFMDGMWUT+eWX+q4u3qz+OCGqSLW6opfhHd4pYQ8/5MGqliblLMlqHVAKVG4="
    # Encrypted `GITHUB_TOKEN` variable. The token belongs to developers@spine.io.
    - secure: "bRxztrq1h5MPR1vkL+b9hm8EfQZQtZOjhUWesUyKwF9iY48dfJwk/quZOmLpja5ZJ65YwYstDhpDpeXMG1KxFzpVus/VewIkEwAYv48TzZrJPv36rwy/ZK69zX7lyFppQOa9dUJfQqI6cYSiCW7GklhI4VXCyWEuzr7MBYEoRVCW+maIpUJGN4r+OehxBLsHDawiQJATvYdyadcEnyrAtCL7Iva099qKw+DCrXEXCxdmN1wgyGrYRTdYuLER3I5oc8yWSxmhwWrKfDUiVnSKRe6ZsnPbDrjpV3sVEdwvq/I7socGHLnoQMCw6zSw5zbohKicTC+QuWUlaJHJxquw6XjgurgX79JPLKLEviYBhSFZgW0Ueyb9SC/jbDd2SvU61PokesBt2MDxWZhr+AocHFD7dU3FpStFs8dNd59oOES5Fxz0iL1kCsCrEKvbK6UcUf67qTEFLt+8RWmOpyPQmvlqoZNqycRag2DAV1iSQgCvPqNjzX7MA/kQxgDjYTR8/oGTwzvvsMcS+6ycKzy/7MM5Nv3irVx35S5qhhazaULSCdQAPZqVqYg5u8N1AacwoDp0laRCw7djLuwpGOjq8cIVfRIvZ4vLiuxrLTZbKtzMYkAU8DZcmcNzVAWq2Zudrlrl6b7RRcVQAVlfSqQsFaKeNirwihsOr3ru4izA4W8="
    # This email is used as a commit author email when updating the Javadoc hosted on GitHub Pages.
    # See `scripts/update-gh-pages.gradle`
    - FORMAL_GIT_HUB_PAGES_AUTHOR: "developers@spine.io"
    - REPO_SLUG: "$TRAVIS_REPO_SLUG"

before_install:
  - chmod +x gradlew
  - chmod +x config/scripts/register-ssh-key.sh
  - chmod +x ./config/scripts/publish-artifacts.sh
  # Decrypt and un-archive Maven and Google Cloud credentials and an RSA private key (deploy_key_rsa).
  # See also: https://github.com/SpineEventEngine/SpineEventEngine.github.io/wiki/Encrypting-credential-files-for-Travis
  - openssl aes-256-cbc -K $encrypted_e308efbe7a9a_key -iv $encrypted_e308efbe7a9a_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
  - chmod 600 deploy_key_rsa

install:
  - ./gradlew assemble --info --stacktrace

script:
  - ./gradlew check --info --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - chmod +x ./config/scripts/upload-artifacts.sh
  - ./config/scripts/upload-artifacts.sh
